export enum AuditAction {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  RESTORE = "RESTORE",
}

export enum EntityType {
  ACCOUNT = "ACCOUNT",
  AUTH = "AUTH",
  COMPANY = "COMPANY",
  EMPLOYEE = "EMPLOYEE",
  EXPENSE = "EXPENSE",
  INVENTORY = "INVENTORY",
  INVENTORYADJUSTMENT = "INVENTORYADJUSTMENT",
  LOAN = "LOAN",
  PARTNER = "PARTNER",
  PURCHASE = "PURCHASE",
  ROLE = "ROLE",
  SALE = "SALE",
  WAREHOUSE = "WAREHOUSE",
}
